name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Start Docker Compose
      run: docker-compose up -d
      working-directory: app

    - name: Run tests
      working-directory: app
      id: test
      run: |
        python -m unittest discover -s ./

    - name: Stop Docker Compose
      run: docker-compose down
      working-directory: app

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      if: steps.test.outcome == 'success'
      run: |
        IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/noteapp"
        VERSION="${{ env.NEW_VERSION }}"
        docker tag roybidani/noteapp:latest "$IMAGE_NAME:$VERSION"
        docker push "$IMAGE_NAME:$VERSION"

    - name: Clean up
      run: |
        docker stop note-app-container || true
        docker rm note-app-container || true
        docker rmi note-app || true

