name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Start Docker Compose
      run: docker-compose up -d
      working-directory: app

    - name: Run tests
      working-directory: app
      run: |
        python -m unittest discover -s ./

    - name: Stop Docker Compose
      run: docker-compose down
      working-directory: app

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to production
      run: |
        # Add deployment steps here, e.g., Docker build and push, deploy to server, etc.

