name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Start Docker Compose
      run: docker-compose up -d
      working-directory: app

    - name: Run tests
      working-directory: app
      id: test
      run: |
        python -m unittest discover -s ./

    - name: Stop Docker Compose
      run: docker-compose down
      working-directory: app
      
    - name: Set version
      run: echo "NEW_VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker tag app_web "roybidani/noteapp:${{ env.NEW_VERSION }}"
        docker push "roybidani/noteapp:${{ env.NEW_VERSION }}"

    - name: Clean up
      run: |
        docker stop app_web_1 || true
        docker rm app_web_1 || true
        docker rmi app_web || true
